<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CPS.Application\CPS.Application.csproj" />
      <ProjectReference Include="..\CPS.Domain\CPS.Domain.csproj" />
      <ProjectReference Include="..\CPS.Infrastructure\CPS.Infrastructure.csproj" />
    </ItemGroup>

</Project>
